### ISSUE TITLE
No handlers could be found for logger "visdom"

### ISSUE THREAD

**Issue by jinzhenmu** [TAMU-VITA/EnlightenGAN#47]
- when i use the code  python3 scripts/script.py --predict

- i happens that:
Total number of parameters: 8636675
-----------------------------------------------
model [SingleGANModel] was created
No handlers could be found for logger "visdom"
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/visdom/__init__.py", line 711, in _send
    data=json.dumps(msg),
  File "/usr/local/lib/python2.7/dist-packages/visdom/__init__.py", line 677, in _handle_post
    r = self.session.post(url, data=data)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f31cc8c66d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
0

**Comment by surajpaib** [comment]
You need to run the visdom server using 
```
nohup python -m visdom.server -port=8097

```
Before running the script you mentioned
