### ISSUE TITLE
    assert(torch.cuda.is_available()) AssertionError

### ISSUE THREAD

**Issue by manvirvirk** [TAMU-VITA/EnlightenGAN#50]
hi, can you solve the error i m getting, whole traceback is:
train.py:10: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(stream)
CustomDatasetDataLoader
dataset [UnalignedDataset] was created
#training images = 20
single
Traceback (most recent call last):
  File "train.py", line 19, in <module>
    model = create_model(opt)
  File "D:\EnlightenGAN-master\models\models.py", line 36, in create_model
    model.initialize(opt)
  File "D:\EnlightenGAN-master\models\single_model.py", line 57, in initialize
    opt.ngf, opt.which_model_netG, opt.norm, not opt.no_dropout, self.gpu_ids, skip=skip, opt=opt)
  File "D:\EnlightenGAN-master\models\networks.py", line 86, in define_G
    assert(torch.cuda.is_available())
AssertionError

**Comment by yueruchen** [comment]
You don't successfully install pytorch with cuda so `torch.cuda.is_available` return False
