### ISSUE TITLE
Train with cycle_gan model

### ISSUE THREAD

**Issue by GuoLanqing** [TAMU-VITA/EnlightenGAN#63]
When I change the training model to `--model cycle_gan`, this error will occur.
```
Traceback (most recent call last):
  File "train.py", line 19, in <module>
    model = create_model(opt)
  File "/home/xxx/projects/EnlightenGAN/models/models.py", line 36, in create_model
    model.initialize(opt)
  File "/home/xxx/projects/EnlightenGAN/models/cycle_gan_model.py", line 31, in initialize
    self.vgg_loss = networks.PerceptualLoss()
TypeError: __init__() missing 1 required positional argument: 'opt'
```
Have you encountered this problem? Is there any solution? Many thanks.

**Comment by yueruchen** [comment]
I suggest you directly use the original cyclegan repo.
